parse: - got rid of warnings - command line parameters - c compile - f file input - r run (1) - r10 run 10 times - when exiting the (byte) exitcode of the last program is returned

diff --git a/65lisp/rrasm b/65lisp/rrasm
--- a/65lisp/rrasm
+++ b/65lisp/rrasm
@@ -18,6 +18,8 @@ echo "unix> ./tap $*"
 name=$1
 shift
 
+echo "params: $@"
+
 rm $name.map  2>/dev/null
 rm $name.o    2>/dev/null
 rm $name.s    2>/dev/null
@@ -29,7 +31,7 @@ rm fil
 # TODO: seems impossible to pass in args to asm 
 #         -D RUNTIMES=10 cannot, isn't set
 
-( cl65 -C sim6502-rrasm.cfg -r -Oirs $* $OPTS '-D__AUTORUN__=$C7' -t sim6502 $name.c $name-asm.asm -o $name.sim -vm -m $name.map 2>&1 | sed 's/(\([0-9]\+\))/:\1/g' ) || (echo "??????????????? FAILED ???????????"; exit 72)
+( cl65 -C sim6502-rrasm.cfg -r -Oirs $OPTS '-D__AUTORUN__=$C7' -t sim6502 $name.c $name-asm.asm -o $name.sim -vm -m $name.map 2>&1 | sed 's/(\([0-9]\+\))/:\1/g' ) || (echo "??????????????? FAILED ???????????"; exit 72)
 
 # generate .s file
 echo "--gen .s--"
