sprite: better optimiation

diff --git a/65lisp/tap b/65lisp/tap
--- a/65lisp/tap
+++ b/65lisp/tap
@@ -24,13 +24,17 @@ rm fil
 # TODO: ld65 -D __GRAB__=1 to grab graphics memory =>44K (37K)
 # TODO: linker -D __AUTORUN__=$C7
 
-( cl65 -Or $* $OPTS '-D__AUTORUN__=$C7' -t atmos $name.c vm-asm.s -o $name.tap -vm -m $name.map 2>&1 | sed 's/(\([0-9]\+\))/:\1/g' ) || (echo "??????????????? FAILED ???????????"; exit 72)
+( cl65 -r -Oirs $* $OPTS '-D__AUTORUN__=$C7' -t atmos $name.c vm-asm.s -o $name.tap -vm -m $name.map 2>&1 | sed 's/(\([0-9]\+\))/:\1/g' ) || (echo "??????????????? FAILED ???????????"; exit 72)
 
-cc65 -O -Or $OPTS -T $name.c vm-asm.s 2>/dev/null # generate .s file
+# generate .s file
+echo "--gen .s--"
+#rm $name.s
+cc65 -r -Oirs $OPTS -T $name.c vm-asm.s 2>/dev/null
+ls -l $name.s
 
 echo "`./wcode $name.c ` LOC of $name  C-code (wc: `wc $name.c`"
 
-cl65 -vm -m $name.map $name.o
+#cl65 -vm -m $name.map $name.o
 
 ls -l $name.o $name.tap
 
